# Generated by Django 2.0.6 on 2018-07-29 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('intro', models.CharField(max_length=200, verbose_name='简介')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('content', models.TextField(verbose_name='博客正文')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('read', models.IntegerField(default=0, verbose_name='阅读量')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类')),
                ('remark', models.CharField(max_length=50, verbose_name='描述')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(default=0, verbose_name='用户id')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='Loginlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classify', models.IntegerField(default=1, verbose_name='分类1为登录,2为登出')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登录登出时间')),
                ('ip', models.CharField(max_length=20, null=True, verbose_name='ip地址')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签')),
                ('remark', models.CharField(max_length=50, verbose_name='描述')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=50, verbose_name='电话')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('loginFailed', models.IntegerField(default=0, verbose_name='登录失败次数')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('creatIp', models.CharField(max_length=20, null=True, verbose_name='ip地址')),
            ],
        ),
        migrations.CreateModel(
            name='Viewlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(default=0, verbose_name='用户id')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='查看时间')),
                ('ip', models.CharField(max_length=20, null=True, verbose_name='ip地址')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog', verbose_name='博客')),
            ],
        ),
        migrations.AddField(
            model_name='loginlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User'),
        ),
        migrations.AddField(
            model_name='blog',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Catagory', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='标签'),
        ),
    ]
