# Generated by Django 2.0.6 on 2018-07-29 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='查看时间')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='邮箱')),
                ('code', models.CharField(max_length=20, null=True, verbose_name='验证码')),
                ('verifyFailed', models.IntegerField(default=0, verbose_name='验证失败次数')),
                ('success', models.BooleanField(default=False, verbose_name='是否验证成功')),
                ('ip', models.CharField(max_length=20, null=True, verbose_name='ip地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User')),
            ],
        ),
    ]
