# Generated by Django 2.1.11 on 2019-12-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, null=True, verbose_name='ip地址')),
                ('remark', models.CharField(max_length=50, verbose_name='描述')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='查看时间')),
            ],
        ),
    ]
